[package]
name = "xtask"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
cargo_metadata = "0.23.1"
clap = { version = "4.5.57", features = ["derive", "env"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
release_plz_core = "0.36.11"
git2 = "0.20.2"
tempfile = "3.23.0"
toml = "0.8"
